import { auth, db, CLOUDINARY, ADMIN_UID, ADMIN_EMAIL } from './firebase-config.js';
import { defaultCategories, defaultOffers, defaultProducts, defaultReviews, defaultSettings } from './default-data.js';
import { currency, parseJSONSafe, qs, qsa, toast } from './utils.js';
import { onAuthStateChanged, signOut } from 'https://www.gstatic.com/firebasejs/10.14.1/firebase-auth.js';
import { collection, getDocs, doc, getDoc, setDoc, addDoc, updateDoc, deleteDoc, serverTimestamp, query, where, limit } from 'https://www.gstatic.com/firebasejs/10.14.1/firebase-firestore.js';

const state = { products: [], categories: [], offers: [], reviews: [], requests: [], orders: [], settings: defaultSettings, currentUser: null };
const serviceStatuses = ['تم الاستلام','تم التواصل','جارٍ المعاينة','جارٍ التنفيذ','تم الإنجاز','ملغي'];
const orderStatuses = ['تم الاستلام','تم التواصل','جارٍ التجهيز','جارٍ التنفيذ','تم الإنجاز','ملغي'];

function switchTab(tab) { qsa('.sidebar-link').forEach(btn => btn.classList.toggle('active', btn.dataset.tab === tab)); qsa('.tab-panel').forEach(panel => panel.classList.toggle('active', panel.id === `tab-${tab}`)); }
function renderMetrics() { const waiting = [...state.requests, ...state.orders].filter(item => item.status !== 'تم الإنجاز' && item.status !== 'ملغي').length; qs('#dashboardMetrics').innerHTML = [['طلبات الخدمات', state.requests.length],['طلبات المتجر', state.orders.length],['الطلبات الجارية', waiting],['المنتجات', state.products.length]].map(([label, value]) => `<article class="metric-card"><strong>${value}</strong><span>${label}</span></article>`).join(''); }
async function syncTrackingStatus(row, status, note) { const snap = await getDocs(query(collection(db, 'publicTracking'), where('trackingCode', '==', row?.trackingCode || ''), limit(1))); if (!snap.empty) await updateDoc(doc(db, 'publicTracking', snap.docs[0].id), { status, note: note || row.note || snap.docs[0].data().note || '', updatedAt: serverTimestamp() }); }

function renderRequests() {
  qs('#requestsTable').innerHTML = state.requests.length ? state.requests.map(item => `<tr><td><strong>${item.requestNo || item.id}</strong><br><small>${item.trackingCode || ''}</small><br><span class="type-pill">خدمة</span></td><td>${item.customerName || '-'}<br><small>${item.customerPhone || ''}</small></td><td>${item.serviceType || '-'}</td><td>${item.area || '-'}</td><td><select class="input select status-select" data-id="${item.id}">${serviceStatuses.map(s => `<option value="${s}" ${item.status === s ? 'selected' : ''}>${s}</option>`).join('')}</select></td><td class="table-actions"><button class="btn btn-secondary update-request" data-id="${item.id}">تحديث</button><button class="btn btn-light delete-request" data-id="${item.id}">حذف</button></td></tr>`).join('') : `<tr><td colspan="6"><div class="empty-state">لا توجد طلبات خدمات بعد.</div></td></tr>`;
  qsa('.update-request').forEach(btn => btn.onclick = async () => { const id = btn.dataset.id; const status = qs(`.status-select[data-id="${id}"]`).value; const row = state.requests.find(x => x.id === id); await updateDoc(doc(db, 'serviceRequests', id), { status, updatedAt: serverTimestamp() }); await syncTrackingStatus(row, status); toast('تم تحديث حالة طلب الخدمة.'); await loadAll(); });
  qsa('.delete-request').forEach(btn => btn.onclick = async () => { if (!confirm('حذف طلب الخدمة؟')) return; await deleteDoc(doc(db, 'serviceRequests', btn.dataset.id)); toast('تم حذف الطلب.'); await loadAll(); });
}
function renderOrders() {
  qs('#ordersTable').innerHTML = state.orders.length ? state.orders.map(item => `<tr><td><strong>${item.orderNo || item.requestNo || item.id}</strong><br><small>${item.trackingCode || ''}</small><br><span class="type-pill gold">متجر</span></td><td>${item.customerName || '-'}<br><small>${item.customerPhone || ''}</small></td><td>${(item.items || []).slice(0, 2).map(x => `${x.name} × ${x.qty}`).join('، ')}${(item.items || []).length > 2 ? ' ...' : ''}</td><td><strong>${currency(item.total || 0)}</strong><br><small>${item.itemsCount || 0} منتج</small></td><td><select class="input select order-status-select" data-id="${item.id}">${orderStatuses.map(s => `<option value="${s}" ${item.status === s ? 'selected' : ''}>${s}</option>`).join('')}</select></td><td class="table-actions"><button class="btn btn-secondary update-order" data-id="${item.id}">تحديث</button><button class="btn btn-light delete-order" data-id="${item.id}">حذف</button></td></tr>`).join('') : `<tr><td colspan="6"><div class="empty-state">لا توجد طلبات متجر بعد.</div></td></tr>`;
  qsa('.update-order').forEach(btn => btn.onclick = async () => { const id = btn.dataset.id; const status = qs(`.order-status-select[data-id="${id}"]`).value; const row = state.orders.find(x => x.id === id); await updateDoc(doc(db, 'orders', id), { status, updatedAt: serverTimestamp() }); await syncTrackingStatus(row, status); toast('تم تحديث حالة طلب المتجر.'); await loadAll(); });
  qsa('.delete-order').forEach(btn => btn.onclick = async () => { if (!confirm('حذف طلب المتجر؟')) return; await deleteDoc(doc(db, 'orders', btn.dataset.id)); toast('تم حذف طلب المتجر.'); await loadAll(); });
}
function renderProducts() { qs('#productsTable').innerHTML = state.products.length ? state.products.map(item => `<tr><td><strong>${item.name}</strong><br><small>${item.group || ''}</small></td><td>${item.category || '-'}</td><td>${currency(item.price)}</td><td>${item.discountPrice ? currency(item.discountPrice) : '-'}</td><td class="table-actions"><button class="btn btn-secondary edit-product" data-id="${item.id}">تعديل</button><button class="btn btn-light delete-product" data-id="${item.id}">حذف</button></td></tr>`).join('') : `<tr><td colspan="5"><div class="empty-state">لا توجد منتجات بعد.</div></td></tr>`; qsa('.edit-product').forEach(btn => btn.onclick = () => fillProductForm(btn.dataset.id)); qsa('.delete-product').forEach(btn => btn.onclick = async () => { if (!confirm('حذف المنتج؟')) return; await deleteDoc(doc(db, 'products', btn.dataset.id)); await loadAll(); }); }
function updateCategorySelectors() { const categories = state.categories.map(c => c.name); qs('#productCategory').innerHTML = categories.map(name => `<option value="${name}">${name}</option>`).join('') || '<option value="">بدون</option>'; const selected = qs('#productCategory').value || categories[0]; const category = state.categories.find(c => c.name === selected); qs('#productGroup').innerHTML = (category?.groups || []).map(g => `<option value="${g}">${g}</option>`).join('') || '<option value="">بدون</option>'; }
function renderCategories() { qs('#categoriesTable').innerHTML = state.categories.length ? state.categories.map(item => `<tr><td><strong>${item.name}</strong></td><td>${(item.groups || []).join('، ')}</td><td class="table-actions"><button class="btn btn-light delete-category" data-id="${item.id}">حذف</button></td></tr>`).join('') : `<tr><td colspan="3"><div class="empty-state">لا توجد أقسام بعد.</div></td></tr>`; qsa('.delete-category').forEach(btn => btn.onclick = async () => { if (!confirm('حذف القسم؟')) return; await deleteDoc(doc(db, 'categories', btn.dataset.id)); await loadAll(); }); updateCategorySelectors(); }
function renderOffers() { qs('#offersTable').innerHTML = state.offers.length ? state.offers.map(item => `<tr><td><strong>${item.title}</strong></td><td>${item.discount || 0}%</td><td class="table-actions"><button class="btn btn-secondary edit-offer" data-id="${item.id}">تعديل</button><button class="btn btn-light delete-offer" data-id="${item.id}">حذف</button></td></tr>`).join('') : `<tr><td colspan="3"><div class="empty-state">لا توجد عروض بعد.</div></td></tr>`; qsa('.edit-offer').forEach(btn => btn.onclick = () => fillOfferForm(btn.dataset.id)); qsa('.delete-offer').forEach(btn => btn.onclick = async () => { if (!confirm('حذف العرض؟')) return; await deleteDoc(doc(db, 'offers', btn.dataset.id)); await loadAll(); }); }
function renderReviews() { qs('#reviewsTable').innerHTML = state.reviews.length ? state.reviews.map(item => `<tr><td>${item.name}</td><td>${item.rating}</td><td>${item.approved ? 'معتمد' : 'قيد المراجعة'}</td><td class="table-actions"><button class="btn btn-secondary toggle-review" data-id="${item.id}">${item.approved ? 'إلغاء الاعتماد' : 'اعتماد'}</button><button class="btn btn-light delete-review" data-id="${item.id}">حذف</button></td></tr>`).join('') : `<tr><td colspan="4"><div class="empty-state">لا توجد تقييمات بعد.</div></td></tr>`; qsa('.toggle-review').forEach(btn => btn.onclick = async () => { const item = state.reviews.find(x => x.id === btn.dataset.id); await updateDoc(doc(db, 'reviews', btn.dataset.id), { approved: !item.approved, updatedAt: serverTimestamp() }); await loadAll(); }); qsa('.delete-review').forEach(btn => btn.onclick = async () => { await deleteDoc(doc(db, 'reviews', btn.dataset.id)); await loadAll(); }); }
function fillSettings() { qs('#companyName').value = state.settings.companyName || ''; qs('#companySummary').value = state.settings.companySummary || ''; qs('#publicUrl').value = state.settings.publicUrl || ''; qs('#notificationEmails').value = (state.settings.notificationEmails || []).join(', '); qs('#cloudinaryCloudName').value = state.settings.cloudinary?.cloudName || CLOUDINARY.cloudName || ''; qs('#cloudinaryUploadPreset').value = state.settings.cloudinary?.uploadPreset || CLOUDINARY.uploadPreset || ''; qs('#contactPhones').value = JSON.stringify(state.settings.contactPhones || [], null, 2); qs('#whatsappNumbers').value = JSON.stringify(state.settings.whatsappNumbers || [], null, 2); qs('#socialLinks').value = JSON.stringify(state.settings.socialLinks || {}, null, 2); qs('#legalBlocks').value = JSON.stringify(state.settings.legalBlocks || [], null, 2); }
function fillProductForm(id) { const item = state.products.find(x => x.id === id); if (!item) return; qs('#productId').value = item.id; qs('#productName').value = item.name; qs('#productPrice').value = item.price; qs('#productDiscountPrice').value = item.discountPrice || ''; qs('#productCategory').value = item.category; updateCategorySelectors(); qs('#productGroup').value = item.group || ''; qs('#productBadge').value = item.badge || ''; qs('#productAvailable').value = String(item.available !== false); qs('#productDescription').value = item.description || ''; qs('#productImage').value = item.image || ''; }
function fillOfferForm(id) { const item = state.offers.find(x => x.id === id); if (!item) return; qs('#offerId').value = item.id; qs('#offerTitle').value = item.title; qs('#offerDescription').value = item.description; qs('#offerDiscount').value = item.discount || 0; qs('#offerFeatured').value = String(item.featured !== false); }
async function loadAll() { const [productsSnap, categoriesSnap, offersSnap, reviewsSnap, requestsSnap, ordersSnap, settingsSnap] = await Promise.all([getDocs(collection(db, 'products')), getDocs(collection(db, 'categories')), getDocs(collection(db, 'offers')), getDocs(collection(db, 'reviews')), getDocs(collection(db, 'serviceRequests')), getDocs(collection(db, 'orders')), getDoc(doc(db, 'settings', 'site'))]); state.products = productsSnap.empty ? defaultProducts.map((item, i) => ({ id:`demo-p-${i}`, ...item })) : productsSnap.docs.map(d => ({ id:d.id, ...d.data() })); state.categories = categoriesSnap.empty ? defaultCategories.map((item, i) => ({ id:`demo-c-${i}`, ...item })) : categoriesSnap.docs.map(d => ({ id:d.id, ...d.data() })); state.offers = offersSnap.empty ? defaultOffers.map((item, i) => ({ id:`demo-o-${i}`, ...item })) : offersSnap.docs.map(d => ({ id:d.id, ...d.data() })); state.reviews = reviewsSnap.empty ? defaultReviews.map((item, i) => ({ id:`demo-r-${i}`, ...item })) : reviewsSnap.docs.map(d => ({ id:d.id, ...d.data() })); state.requests = requestsSnap.empty ? [] : requestsSnap.docs.map(d => ({ id:d.id, ...d.data() })); state.orders = ordersSnap.empty ? [] : ordersSnap.docs.map(d => ({ id:d.id, ...d.data() })); state.settings = settingsSnap.exists() ? { ...defaultSettings, ...settingsSnap.data() } : defaultSettings; state.settings.cloudinary = { ...defaultSettings.cloudinary, ...(state.settings.cloudinary || {}) }; renderMetrics(); renderRequests(); renderOrders(); renderCategories(); renderProducts(); renderOffers(); renderReviews(); fillSettings(); }
async function ensureAdminRecord(user) { await setDoc(doc(db, 'admins', user.uid), { uid: user.uid, email: user.email, active: true, updatedAt: serverTimestamp() }, { merge: true }); }
function getCloudinaryConfig() { return { cloudName:(state.settings.cloudinary?.cloudName || CLOUDINARY.cloudName || '').trim(), uploadPreset:(state.settings.cloudinary?.uploadPreset || CLOUDINARY.uploadPreset || '').trim() }; }
function initCloudinary() { const button = qs('#openCloudinaryBtn'); if (!button || !window.cloudinary) return; button.addEventListener('click', () => { const config = getCloudinaryConfig(); window.cloudinary.openUploadWidget({ cloudName:config.cloudName, uploadPreset:config.uploadPreset, sources:['local','camera','url'], multiple:false, folder:'shm-products' }, (error, result) => { if (!error && result && result.event === 'success') { qs('#productImage').value = result.info.secure_url; toast('تم رفع الصورة بنجاح.'); } }); }); }
async function autoCreateCategoryIfNeeded(name, group) { if (!name) return; const existing = state.categories.find(item => item.name === name); if (!existing) { await addDoc(collection(db, 'categories'), { name, groups: group ? [group] : [], createdAt: serverTimestamp(), updatedAt: serverTimestamp() }); return; } const groups = existing.groups || []; if (group && !groups.includes(group) && !String(existing.id).startsWith('demo-')) await updateDoc(doc(db, 'categories', existing.id), { groups:[...groups, group], updatedAt: serverTimestamp() }); }
function bindForms() {
  qsa('.sidebar-link').forEach(btn => btn.onclick = () => switchTab(btn.dataset.tab)); qs('#productCategory').addEventListener('change', updateCategorySelectors);
  qs('#productForm').addEventListener('submit', async e => { e.preventDefault(); const id = qs('#productId').value; const category = qs('#productCategory').value.trim(); const group = qs('#productGroup').value.trim(); await autoCreateCategoryIfNeeded(category, group); const payload = { name: qs('#productName').value.trim(), price: Number(qs('#productPrice').value || 0), discountPrice: Number(qs('#productDiscountPrice').value || 0), category, group, badge: qs('#productBadge').value.trim(), available: qs('#productAvailable').value === 'true', description: qs('#productDescription').value.trim(), image: qs('#productImage').value.trim(), published:true, updatedAt: serverTimestamp() }; if (id && !String(id).startsWith('demo-')) await updateDoc(doc(db, 'products', id), payload); else await addDoc(collection(db, 'products'), { ...payload, createdAt: serverTimestamp() }); e.target.reset(); qs('#productId').value=''; await loadAll(); });
  qs('#categoryForm').addEventListener('submit', async e => { e.preventDefault(); const payload = { name: qs('#categoryName').value.trim(), groups: qs('#categoryGroups').value.split(',').map(x => x.trim()).filter(Boolean), updatedAt: serverTimestamp() }; await addDoc(collection(db, 'categories'), { ...payload, createdAt: serverTimestamp() }); e.target.reset(); await loadAll(); });
  qs('#offerForm').addEventListener('submit', async e => { e.preventDefault(); const id = qs('#offerId').value; const payload = { title: qs('#offerTitle').value.trim(), description: qs('#offerDescription').value.trim(), discount: Number(qs('#offerDiscount').value || 0), featured: qs('#offerFeatured').value === 'true', updatedAt: serverTimestamp() }; if (id && !String(id).startsWith('demo-')) await updateDoc(doc(db, 'offers', id), payload); else await addDoc(collection(db, 'offers'), { ...payload, createdAt: serverTimestamp() }); e.target.reset(); qs('#offerId').value=''; await loadAll(); });
  qs('#settingsForm').addEventListener('submit', async e => { e.preventDefault(); const payload = { companyName: qs('#companyName').value.trim(), companySummary: qs('#companySummary').value.trim(), publicUrl: qs('#publicUrl').value.trim(), notificationEmails: qs('#notificationEmails').value.split(',').map(x => x.trim()).filter(Boolean), cloudinary:{ cloudName: qs('#cloudinaryCloudName').value.trim(), uploadPreset: qs('#cloudinaryUploadPreset').value.trim() }, contactPhones: parseJSONSafe(qs('#contactPhones').value, []), whatsappNumbers: parseJSONSafe(qs('#whatsappNumbers').value, []), socialLinks: parseJSONSafe(qs('#socialLinks').value, {}), legalBlocks: parseJSONSafe(qs('#legalBlocks').value, []), updatedAt: serverTimestamp() }; await setDoc(doc(db, 'settings', 'site'), payload, { merge:true }); toast('تم حفظ الإعدادات.'); await loadAll(); });
  qs('#logoutBtn').addEventListener('click', async () => { await signOut(auth); location.href='admin-login.html'; });
}
onAuthStateChanged(auth, async user => { if (!user) { location.href='admin-login.html'; return; } const allowed = user.uid === ADMIN_UID || (user.email || '').toLowerCase() === ADMIN_EMAIL.toLowerCase(); if (!allowed) { location.href='admin-login.html'; return; } state.currentUser = user; qs('#adminUserBadge').textContent = user.email || 'Admin'; await ensureAdminRecord(user); bindForms(); initCloudinary(); await loadAll(); });
